import Head from "next/head"; 
import Image from "next/image";
import { Container } from "react-bootstrap"; 

export default function AboutFounder( ) {
  return (
    <>
      <Head>
        <title>About | Sridhar Musical Institute</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.ico"  />
      </Head>
      <main>
        <Container>

        
        <h3 className="section-title"> About the Founder </h3>
        <div className="founder-img-div">
        <Image
          className="founder-img"
          alt="founder" 
          src='/images/steve.jpg' 
          width='200' 
          height='200'
          layout='intrinsic'
          />
        </div>
       
        <p className="my-5">
          Steves Unknowns captivating audiences in their journey of great
          musical performances, and still savoring it in its purest sense is a
          band engraved in the annals of Bangalore’s music vault, deep in its
          tradition and history. <br />
          <br />
          The band name by founder – Sridhar Stephen Joseph aka Steve – speaks
          for itself, as he goes down memory-lane recalling the birth of the
          name. “Once upon a time, backstage, preparing to come-on for the first
          time as a band, when the announcer interrupted me, demanding a band
          name. I paused for a moment, thinking deep – my mind was absolutely
          blank, regarding names–I was only thinking about the set list, not a
          band name in sight yet, it dawned on me the importance of this
          situation, we looked at each other, still no band name?We could not go
          unknown to the audience…the word Unknown for some strange reason
          echoed in my head, in-fact I’ve always believed I’m Unknown and from a
          deeper sense, I replied with ease, we are “The Unknowns”. <br />
          <br />
          Since then, through glorious years of performing in and around India,
          as-well-as various parts of the world, until the band sang its final
          swan song, The Unknowns have jammed to the tune of many a versatile
          ear, be it fans of Rock N’Roll, Hard Rock, Heavy Metal, Blues, Fusion,
          Pop to those ardent Indian Raga fans–lashing out music in their
          trademark style, improvising western feel with strong Indian roots,
          leaving audiences moving and grooving to The Unknowns–who were not
          just a band, but a band of brothers!
        </p>

        
        </Container>
      </main>
    </>
  );
}
 
