import Head from 'next/head'; 
import Map from '../components/Map'; 
import Hero from "../components/hero";
import About from "../components/about";
import Classes from "../components/classes";
import Contact from "../components/contact";
import { getAllPosts } from '../lib/api'   

const DEFAULT_CENTER = [12.9708658, 77.6278365]

export default function Home({allPosts }) {
  return (
    < >
      <Head>
        <title>Sridhar Music Institute</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.ico" />
      </Head>

      <main >

      <Hero />
        <About />
        <Classes posts={allPosts}/>
        <Contact />
        

        <Map className="map mt-5 mb-0" center={DEFAULT_CENTER} zoom={17} scrollWheelZoom={false}>
          {({ TileLayer, Marker, Popup }) => (
            <>
              <TileLayer
                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                attribution="&copy; <a href=&quot;http://osm.org/copyright&quot;>OpenStreetMap</a> contributors"
              />
              <Marker position={DEFAULT_CENTER}>
                <Popup>
                  Sridhar Music Institute
                </Popup>
              </Marker>
            </>
          )}
        </Map>

    
 
      </main>
 
    </ >
  )
}



export async function getStaticProps() {
  const allPosts = getAllPosts([
    'title',
    'date',
    'slug',
    'img', 
  ])

  return {
    props: { allPosts },
  }
}